### ISSUE TITLE
Suggestion for naming variables

### ISSUE THREAD

**Issue by PhyllisWong** [Keto-Eating/Keto-Recipe-API#59] opened 2018-11-26 23:19 UTC
it's good practice to indicate that it's an array of userIds instead of users. it's probably not something for this PR, perhaps a refactor PR, but perhaps something like `favoritedUserIds`

_Originally posted by @lesliekimm in https://github.com/Keto-Eating/Keto-Recipe-API/pull/47_

**Comment by nsafai** [comment] 2019-01-28 19:17
duplicate of https://github.com/Keto-Eating/Keto-Recipe-API/issues/60

**Closed** 2019-01-28 19:17 UTC
