### ISSUE TITLE
refactor the UI for cart and grocerylist

### ISSUE THREAD

**Issue by PhyllisWong** [Keto-Eating/Keto-Recipe-API#63] opened 2018-11-27 19:44 UTC
deliverable by Dec 4th

**Comment by nsafai** [comment] 2019-01-28 19:11
@PhyllisWong can you add some info to this card? Right now it doesn't have enough info to be actionable. If this is now a duplicate of another issue, lets archive it.

**Comment by nsafai** [comment] 2019-01-28 19:12
actually going to close this ticket for now in an effort to clean up our backlog. if u end up adding more info, feel free to reopen it

**Closed by nsafai** 2019-01-28 19:12 UTC
