### ISSUE TITLE
Rename variables in Mongoose calls

### ISSUE THREAD

**Issue by PhyllisWong** [Keto-Eating/Keto-Recipe-API#61] opened 2018-11-26 23:20 UTC
_Originally posted by @lesliekimm in https://github.com/Keto-Eating/Keto-Recipe-API/pull/47_

**Comment by nsafai** [comment] 2019-01-28 19:17
closing as this is a duplicate of https://github.com/Keto-Eating/Keto-Recipe-API/issues/60

**Closed by nsafai** 2019-01-28 19:17 UTC
